export const ArrayAnuncios  = [
    {
        id_anuncio: 1,
        nombre: 'Programador',
        descripcion: 'Analista Programador(a) Base de Trabajo Montero Requisitos Titulado(a) de Ingeniería de Sistemas, Informática o ramas afines. Experiencia en gestión de Base de Datos Oracle, MySQL, SQL Server',
        ubicacion: 'La Paz',
        categoria: 'Informática',
        sueldo: 'No especificado',
        contrato: 'Medio Tiempo',
        modalidad:  'Virtual',
        fec_publi: '01/04/2024',
        fec_venc: '30/04/2024',
        empresa: {
            id_empresa: 1,
            nombre: 'Empresa 1',
            descripcion: 'Empresa 1 descripcion',
            direccion: 'Av.  Empresa 1',
            ubicacion: 'La Paz',
            telefono: '22793434',
            celular: '78988721',
            sitio_web: 'www.empresa1.com',
            verificado: 1,
            img: 'https://png.pngtree.com/template/20191014/ourlarge/pngtree-real-estate-business-logo-template-building-property-development-and-construction-logo-image_317796.jpg'
        },
        estado: 1
    },
    {
        id_anuncio: 2,
        nombre: 'Programador',
        descripcion: 'Analista Programador(a) Base de Trabajo Montero Requisitos Titulado(a) de Ingeniería de Sistemas, Informática o ramas afines. Experiencia en gestión de Base de Datos Oracle, MySQL, SQL Server',
        ubicacion: 'La Paz',
        categoria: 'Informática',
        sueldo: 'No especificado',
        contrato: 'Medio Tiempo',
        modalidad:  'Virtual',
        fec_publi: '01/04/2024',
        fec_venc: '30/04/2024',
        empresa: {
            id_empresa: 1,
            nombre: 'Empresa 1',
            descripcion: 'Empresa 1 descripcion',
            direccion: 'Av.  Empresa 1',
            ubicacion: 'La Paz',
            telefono: '22793434',
            celular: '78988721',
            sitio_web: 'www.empresa1.com',
            verificado: 1,
            img: 'https://png.pngtree.com/template/20191014/ourlarge/pngtree-real-estate-business-logo-template-building-property-development-and-construction-logo-image_317796.jpg'
        },
        estado: 1
    },
    {
        id_anuncio: 3,
        nombre: 'Programador',
        descripcion: 'Analista Programador(a) Base de Trabajo Montero Requisitos Titulado(a) de Ingeniería de Sistemas, Informática o ramas afines. Experiencia en gestión de Base de Datos Oracle, MySQL, SQL Server',
        ubicacion: 'La Paz',
        categoria: 'Informática',
        sueldo: 'No especificado',
        contrato: 'Medio Tiempo',
        modalidad:  'Virtual',
        fec_publi: '01/04/2024',
        fec_venc: '30/04/2024',
        empresa: {
            id_empresa: 1,
            nombre: 'Empresa 1',
            descripcion: 'Empresa 1 descripcion',
            direccion: 'Av.  Empresa 1',
            ubicacion: 'La Paz',
            telefono: '22793434',
            celular: '78988721',
            sitio_web: 'www.empresa1.com',
            verificado: 1,
            img: 'https://png.pngtree.com/template/20191014/ourlarge/pngtree-real-estate-business-logo-template-building-property-development-and-construction-logo-image_317796.jpg'
        },
        estado: 1
    },
    {
        id_anuncio: 3,
        nombre: 'Programador',
        descripcion: 'Analista Programador(a) Base de Trabajo Montero Requisitos Titulado(a) de Ingeniería de Sistemas, Informática o ramas afines. Experiencia en gestión de Base de Datos Oracle, MySQL, SQL Server',
        ubicacion: 'La Paz',
        categoria: 'Informática',
        sueldo: 'No especificado',
        contrato: 'Medio Tiempo',
        modalidad:  'Virtual',
        fec_publi: '01/04/2024',
        fec_venc: '30/04/2024',
        empresa: {
            id_empresa: 1,
            nombre: 'Empresa 1',
            descripcion: 'Empresa 1 descripcion',
            direccion: 'Av.  Empresa 1',
            ubicacion: 'La Paz',
            telefono: '22793434',
            celular: '78988721',
            sitio_web: 'www.empresa1.com',
            verificado: 1,
            img: 'https://png.pngtree.com/template/20191014/ourlarge/pngtree-real-estate-business-logo-template-building-property-development-and-construction-logo-image_317796.jpg'
        },
        estado: 1
    },
    {
        id_anuncio: 4,
        nombre: 'Diseñador',
        descripcion: 'Analista Programador(a) Base de Trabajo Montero Requisitos Titulado(a) de Ingeniería de Sistemas, Informática o ramas afines. Experiencia en gestión de Base de Datos Oracle, MySQL, SQL Server',
        ubicacion: 'La Paz',
        categoria: 'Informática',
        sueldo: 'No especificado',
        contrato: 'Medio Tiempo',
        modalidad:  'Virtual',
        fec_publi: '01/04/2024',
        fec_venc: '30/04/2024',
        empresa: {
            id_empresa: 1,
            nombre: 'Empresa 1',
            descripcion: 'Empresa 1 descripcion',
            direccion: 'Av.  Empresa 1',
            ubicacion: 'La Paz',
            telefono: '22793434',
            celular: '78988721',
            sitio_web: 'www.empresa1.com',
            verificado: 1,
            img: 'https://png.pngtree.com/template/20191014/ourlarge/pngtree-real-estate-business-logo-template-building-property-development-and-construction-logo-image_317796.jpg'
        },
        estado: 1
    },
        
];